### ISSUE TITLE
SEGFAULT in libjavascriptcoregtk-1.0.so.0.16.19

### ISSUE THREAD

**Issue by DreamerDDL** [linuxbuh/linuxbuh#1]
Столкнулся с проблемой SEGFAULT при запуске Конфигуратора 1С на платформе . Небольшой дебаг показал что вылетает в библиотеке libjavascriptcoregtk

```
Thread 1 "1cv8" received signal SIGSEGV, Segmentation fault.
0x00007fffcdb52428 in WTF::String::isolatedCopy() const () from /usr/lib64/libjavascriptcoregtk-1.0.so.0
(gdb) quit

```
Гугул подсказал решение которое, после краткой проверки, работает. Добавить флаг компиляции **-fno-delete-null-pointer-checks** для webkit-2.4.11-r200
```
# GCC 6.4 NULL pointer optimiztion fix 
append-cxxflags $(test-flags-CXX -fno-delete-null-pointer-checks)
```
Платформа - Calculate Linux Desktop 17.12.2 x86_64
GCC - gcc (Gentoo 6.4.0-r1 p1.3) 6.4.0

**Comment by linuxbuh** [comment]
Поправил ebuild
